from datetime import datetime

ai_header_columns = {
    'shopname':{
        'mandatory':True,
        'type':str
    }, 
    'country':{
        'mandatory':True,
        'type':str
    }, 
    'telephone':{
        'mandatory':False,
        'type':str
    }, 
    'roid':{
        'mandatory': True,
        'type': int
    }, 
    'createddatetime':{
        'mandatory': True,
        'type': datetime
    }, 
    'autoauthorized':{
        'mandatory': False,
        'type':bool
    }, 
    'clientname':{
        'mandatory': False,
        'type':str
    }, 
    'vendorname':{
        'mandatory': True,
        'type':str
    }, 
    'payableamount':{
        'mandatory': True,
        'type':float
    }, 
    'subtotal':{
        'mandatory': True,
        'type':float
    }, 
    'taxtotal':{
        'mandatory': True,
        'type':float
    }}

ca_header_columns = {
    "sourcename":{
        "mandatory":True,
        "type":str
    },
    "id":{
        "mandatory":True,
        "type":int
    },
    "id2":{
        "mandatory":False,
        "type":int
    },
    "company":{
        "mandatory":True,
        "type":str
    },
    "case":{
        "mandatory":True,
        "type":str
    },
    "name":{
        "mandatory":True,
        "type":str
    },
    "country":{
        "mandatory":True,
        "type":str
    },
    "aiorderid":{
        "mandatory":True,
        "type":int
    },
    "appointmentdatetime":{
        "mandatory":False,
        "type":datetime
    },
    "createdat":{
        "mandatory":True,
        "type":datetime
    },
    "invoicenumber":{
        "mandatory":True,
        "type":str
    },
    "partstotal":{
        "mandatory":True,
        "type":float
    },
    "labortotal":{
        "mandatory":True,
        "type":float
    },
    "feetotal":{
        "mandatory":True,
        "type":float
    },
    "discounttotal":{
        "mandatory":True,
        "type":float
    },
    "aitaxtotal":{
        "mandatory":True,
        "type":float
    },
    "aitransactionfee":{
        "mandatory":True,
        "type":float
    },
    "shoprebate":{
        "mandatory":True,
        "type":float
    },
    "approvalstatus":{
        "mandatory":True,
        "type":str
    },
    "status":{
        "mandatory":True,
        "type":str
    },
    "amounttopay":{
        "mandatory":True,
        "type":float
    },
    "transfee":{
        "mandatory":True,
        "type":float
    },
    "merchfee":{
        "mandatory":True,
        "type":float
    },
}

rebates = {
    "aamco": {
        "all":0.1
    },
    "americantiredepot":{
        "all":0.08
    },
    "belltransportation":
    {
        "all":0
    },
    "bsro":
    {
        "all":0.105
    },
    "canadiantire":{
        "all":0.09
    },
    "countryclubservice":{
        "all":0
    },
    "discounttire":{
        "all":0.05
    },
    "fleetmanagementservices":
    {
        "all":0.1
    },
    "fullspeedautomotive":{
        "all":0.08
    },
    "gbauto":{
        "all":0.1
    },
    "getspiffy":{
        "all":0.12
    },
    "goodyear":{
        "all":0.1
    },
    "jiffylube":{
        "ca":0.1,
        "us":0.14
    },
    "lesschwab":{
        "all":0.05
    },
    "meineke":{
        "all":0.12
    },
    "monro":{
        "all":0.1
    },
    "mopar":{
        "all":0.1
    },
    "stellantis":{
        "all":0.1
    },
    "mrlube":{
        "all":0.1
    },
    "oilchangers":{
        "all":0
    },
    "pepboys":{
        "all":0.094
    },
    "take5":{
        "all":0.12
    },
    "tbc":{
        "all":0.15
    },
    "unitedfleet":{
        "all":0
    },
    "valvoline":{
        "all":0.15
    }
}
